apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner-ingress
  namespace: workloads
spec:
  virtualhost:
    fqdn: where-for-dinner.perfect300rock.com
  routes:
  - conditions:
    - prefix: /
    services:
    - name: gateway-where-for-dinner
      port: 80
